# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_hizlistokpanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HizliStokPanel(object):
    def setupUi(self, HizliStokPanel):
        HizliStokPanel.setObjectName("HizliStokPanel")
        HizliStokPanel.setWindowModality(QtCore.Qt.NonModal)
        HizliStokPanel.setEnabled(True)
        HizliStokPanel.resize(500, 412)
        HizliStokPanel.setMinimumSize(QtCore.QSize(0, 0))
        HizliStokPanel.setMaximumSize(QtCore.QSize(500, 412))
        HizliStokPanel.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(HizliStokPanel)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(39, 44, 54);\n"
"}\n"
"QFrame QLineEdit{\n"
"max-width:300px;\n"
"height:35px;\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QFrame QLabel{\n"
"color:white;\n"
"font: 9pt \"Nirmala UI\";\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("background-color: rgb(85, 0, 0);\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stok_title_bar_top = QtWidgets.QLabel(self.frame_2)
        self.stok_title_bar_top.setMinimumSize(QtCore.QSize(0, 35))
        self.stok_title_bar_top.setMaximumSize(QtCore.QSize(16777215, 35))
        self.stok_title_bar_top.setStyleSheet("background-color: rgb(85, 0, 0);")
        self.stok_title_bar_top.setText("")
        self.stok_title_bar_top.setObjectName("stok_title_bar_top")
        self.horizontalLayout_2.addWidget(self.stok_title_bar_top)
        self.btn_hizli_stok_cikis = QtWidgets.QPushButton(self.frame_2)
        self.btn_hizli_stok_cikis.setMinimumSize(QtCore.QSize(30, 20))
        self.btn_hizli_stok_cikis.setMaximumSize(QtCore.QSize(20, 30))
        self.btn_hizli_stok_cikis.setStyleSheet("QPushButton{\n"
"background-color: rgb(85, 0, 0);\n"
"color: #000;\n"
"border-style:none;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(71, 78, 93);\n"
"border-style:none;\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 220, 220);\n"
"}")
        self.btn_hizli_stok_cikis.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/20x20/icons/20x20/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_hizli_stok_cikis.setIcon(icon)
        self.btn_hizli_stok_cikis.setObjectName("btn_hizli_stok_cikis")
        self.horizontalLayout_2.addWidget(self.btn_hizli_stok_cikis)
        self.verticalLayout.addWidget(self.frame_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(0, -1, -1, -1)
        self.formLayout.setHorizontalSpacing(30)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.ln_hizliStokAd = QtWidgets.QLineEdit(self.frame)
        self.ln_hizliStokAd.setMinimumSize(QtCore.QSize(300, 35))
        self.ln_hizliStokAd.setMaximumSize(QtCore.QSize(300, 16777215))
        self.ln_hizliStokAd.setStyleSheet("QLineEdit{\n"
"\n"
"background-color: rgb(27, 29, 35);\n"
"    color: rgb(255, 255, 255);\n"
"border-radius: 5px;\n"
"border-bottom: 1px solid rgb(44, 49, 60);\n"
"gridline-color:rgb(255, 170, 0);\n"
"font: 63 italic 9pt \"Segoe UI Semibold\";\n"
"}")
        self.ln_hizliStokAd.setObjectName("ln_hizliStokAd")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ln_hizliStokAd)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.ln_hizliStokMarka = QtWidgets.QLineEdit(self.frame)
        self.ln_hizliStokMarka.setStyleSheet("QLineEdit{\n"
"\n"
"background-color: rgb(27, 29, 35);\n"
"\n"
"border-radius: 5px;\n"
"border-bottom: 1px solid rgb(44, 49, 60);\n"
"gridline-color:rgb(255, 170, 0);\n"
"font: 63 italic 9pt \"Segoe UI Semibold\";\n"
"}")
        self.ln_hizliStokMarka.setObjectName("ln_hizliStokMarka")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ln_hizliStokMarka)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.ln_hizliStokFiyat = QtWidgets.QLineEdit(self.frame)
        self.ln_hizliStokFiyat.setStyleSheet("QLineEdit{\n"
"\n"
"background-color: rgb(27, 29, 35);\n"
"\n"
"border-radius: 5px;\n"
"border-bottom: 1px solid rgb(44, 49, 60);\n"
"gridline-color:rgb(255, 170, 0);\n"
"font: 63 italic 9pt \"Segoe UI Semibold\";\n"
"}")
        self.ln_hizliStokFiyat.setObjectName("ln_hizliStokFiyat")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ln_hizliStokFiyat)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.sp_hizliStokAdet = QtWidgets.QSpinBox(self.frame)
        self.sp_hizliStokAdet.setMinimumSize(QtCore.QSize(300, 35))
        self.sp_hizliStokAdet.setMaximumSize(QtCore.QSize(300, 35))
        self.sp_hizliStokAdet.setStyleSheet("QSpinBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QSpinBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QSpinBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.sp_hizliStokAdet.setObjectName("sp_hizliStokAdet")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sp_hizliStokAdet)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.ln_hizliStokBarkod = QtWidgets.QLineEdit(self.frame)
        self.ln_hizliStokBarkod.setStyleSheet("QLineEdit{\n"
"\n"
"background-color: rgb(27, 29, 35);\n"
"\n"
"border-radius: 5px;\n"
"border-bottom: 1px solid rgb(44, 49, 60);\n"
"gridline-color:rgb(255, 170, 0);\n"
"font: 63 italic 9pt \"Segoe UI Semibold\";\n"
"}")
        self.ln_hizliStokBarkod.setObjectName("ln_hizliStokBarkod")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ln_hizliStokBarkod)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.dt_hizliStok = QtWidgets.QDateTimeEdit(self.frame)
        self.dt_hizliStok.setEnabled(False)
        self.dt_hizliStok.setMinimumSize(QtCore.QSize(300, 35))
        self.dt_hizliStok.setMaximumSize(QtCore.QSize(300, 35))
        self.dt_hizliStok.setStyleSheet("QDateTimeEdit{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QDateTimeEdit:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QDateTimeEdit QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.dt_hizliStok.setObjectName("dt_hizliStok")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.dt_hizliStok)
        self.btn_hizliStokKaydet = QtWidgets.QPushButton(self.frame)
        self.btn_hizliStokKaydet.setMinimumSize(QtCore.QSize(150, 35))
        self.btn_hizliStokKaydet.setMaximumSize(QtCore.QSize(150, 35))
        self.btn_hizliStokKaydet.setStyleSheet("QPushButton{\n"
"background-color: rgb(197, 197, 197);\n"
"color: #000;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 170, 127);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 220, 220);\n"
"}")
        self.btn_hizliStokKaydet.setObjectName("btn_hizliStokKaydet")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.btn_hizliStokKaydet)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout.addWidget(self.frame)
        HizliStokPanel.setCentralWidget(self.centralwidget)

        self.retranslateUi(HizliStokPanel)
        QtCore.QMetaObject.connectSlotsByName(HizliStokPanel)

    def retranslateUi(self, HizliStokPanel):
        _translate = QtCore.QCoreApplication.translate
        HizliStokPanel.setWindowTitle(_translate("HizliStokPanel", "MainWindow"))
        self.label.setText(_translate("HizliStokPanel", "Ürün Adı"))
        self.label_2.setText(_translate("HizliStokPanel", "Marka"))
        self.label_3.setText(_translate("HizliStokPanel", "Fiyat"))
        self.label_4.setText(_translate("HizliStokPanel", "Adet"))
        self.label_5.setText(_translate("HizliStokPanel", "Barkod"))
        self.label_6.setText(_translate("HizliStokPanel", "Tarih"))
        self.btn_hizliStokKaydet.setText(_translate("HizliStokPanel", "Kaydet"))
import files_rc
