# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnaSayfa_(object):
    def setupUi(self, AnaSayfa_):
        AnaSayfa_.setObjectName("AnaSayfa_")
        AnaSayfa_.resize(1466, 779)
        AnaSayfa_.setMinimumSize(QtCore.QSize(1000, 720))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 73, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 61, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(29, 32, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 49, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 73, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 61, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(29, 32, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 49, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 73, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(55, 61, 75))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(29, 32, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 24, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 49, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(44, 49, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(210, 210, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        AnaSayfa_.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        AnaSayfa_.setFont(font)
        AnaSayfa_.setStyleSheet("QMainWindow {background: transparent; }\n"
"QToolTip {\n"
"    color: #ffffff;\n"
"    background-color: rgba(27, 29, 35, 160);\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(AnaSayfa_)
        self.centralwidget.setStyleSheet("background: transparent;\n"
"color: rgb(210, 210, 210);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setStyleSheet("")
        self.frame_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_top = QtWidgets.QFrame(self.frame_main)
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_top.setStyleSheet("background-color: transparent;")
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_toggle = QtWidgets.QFrame(self.frame_top)
        self.frame_toggle.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_toggle.setStyleSheet("background-color: rgb(27, 29, 35);")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_toggle)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_settings = QtWidgets.QPushButton(self.frame_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_settings.sizePolicy().hasHeightForWidth())
        self.btn_settings.setSizePolicy(sizePolicy)
        self.btn_settings.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.btn_settings.setFont(font)
        self.btn_settings.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_settings.setStyleSheet("QPushButton {    \n"
"    background-image: url(:/20x20/icons/20x20/cil-link-alt.png);\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 26px solid rgb(66, 44, 0);\n"
"    background-color: rgb(66, 44, 0);\n"
"    text-align: left;\n"
"    padding-left: 45px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"    border-left: 26px solid rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"    border-left: 26px solid rgb(85, 170, 255);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/20x20/icons/20x20/cil-swap-vertical.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_settings.setIcon(icon)
        self.btn_settings.setObjectName("btn_settings")
        self.verticalLayout_3.addWidget(self.btn_settings)
        self.horizontalLayout_3.addWidget(self.frame_toggle)
        self.frame_top_right = QtWidgets.QFrame(self.frame_top)
        self.frame_top_right.setStyleSheet("background: transparent;")
        self.frame_top_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_right.setObjectName("frame_top_right")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_top_right)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top_btns = QtWidgets.QFrame(self.frame_top_right)
        self.frame_top_btns.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_top_btns.setStyleSheet("background-color: rgba(33, 37, 43, 150);")
        self.frame_top_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_btns.setObjectName("frame_top_btns")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_top_btns)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_label_top_btns = QtWidgets.QFrame(self.frame_top_btns)
        self.frame_label_top_btns.setStyleSheet("background-color: rgb(52, 17, 0);")
        self.frame_label_top_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_label_top_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_top_btns.setObjectName("frame_label_top_btns")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_label_top_btns)
        self.horizontalLayout_10.setContentsMargins(8, 0, 10, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_icon_top_bar = QtWidgets.QFrame(self.frame_label_top_btns)
        self.frame_icon_top_bar.setMaximumSize(QtCore.QSize(30, 30))
        self.frame_icon_top_bar.setStyleSheet("background: transparent;\n"
"background-image: url(:/16x16/icons/16x16/cil-media-eject.png);\n"
"background-position: center;\n"
"background-repeat: no-repeat;")
        self.frame_icon_top_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_icon_top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_icon_top_bar.setObjectName("frame_icon_top_bar")
        self.horizontalLayout_10.addWidget(self.frame_icon_top_bar)
        self.label_title_bar_top = QtWidgets.QLabel(self.frame_label_top_btns)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_title_bar_top.setFont(font)
        self.label_title_bar_top.setStyleSheet("background: transparent;\n"
"margin-left: 5px;\n"
"background-color: rgb(52, 17, 0);")
        self.label_title_bar_top.setObjectName("label_title_bar_top")
        self.horizontalLayout_10.addWidget(self.label_title_bar_top)
        self.horizontalLayout_4.addWidget(self.frame_label_top_btns)
        self.frame_btns_right = QtWidgets.QFrame(self.frame_top_btns)
        self.frame_btns_right.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame_btns_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_btns_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns_right.setObjectName("frame_btns_right")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_btns_right)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_minimize.sizePolicy().hasHeightForWidth())
        self.btn_minimize.setSizePolicy(sizePolicy)
        self.btn_minimize.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    \n"
"    \n"
"    background-color: rgb(29, 29, 29);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(44, 49, 60)\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_minimize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-window-minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimize.setIcon(icon1)
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_5.addWidget(self.btn_minimize)
        self.btn_maximize_restore = QtWidgets.QPushButton(self.frame_btns_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_maximize_restore.sizePolicy().hasHeightForWidth())
        self.btn_maximize_restore.setSizePolicy(sizePolicy)
        self.btn_maximize_restore.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    \n"
"    background-color: rgb(29, 29, 29);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(44, 49, 60)\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_maximize_restore.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-window-maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_maximize_restore.setIcon(icon2)
        self.btn_maximize_restore.setObjectName("btn_maximize_restore")
        self.horizontalLayout_5.addWidget(self.btn_maximize_restore)
        self.btn_close = QtWidgets.QPushButton(self.frame_btns_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close.sizePolicy().hasHeightForWidth())
        self.btn_close.setSizePolicy(sizePolicy)
        self.btn_close.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    \n"
"    background-color: rgb(29, 29, 29);\n"
"}\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(85, 0, 0);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_close.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon3)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_5.addWidget(self.btn_close)
        self.horizontalLayout_4.addWidget(self.frame_btns_right)
        self.verticalLayout_2.addWidget(self.frame_top_btns)
        self.frame_top_info = QtWidgets.QFrame(self.frame_top_right)
        self.frame_top_info.setStyleSheet("background-color: rgb(39, 44, 54);\n"
"background-color: rgb(29, 29, 29);")
        self.frame_top_info.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_info.setObjectName("frame_top_info")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_top_info)
        self.horizontalLayout_8.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_top_info = QtWidgets.QLabel(self.frame_top_info)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_top_info.setFont(font)
        self.label_top_info.setStyleSheet("color: rgb(98, 103, 111);\n"
"background-color: rgb(29, 29, 29);")
        self.label_top_info.setObjectName("label_top_info")
        self.horizontalLayout_8.addWidget(self.label_top_info)
        self.label_top_info_2 = QtWidgets.QLabel(self.frame_top_info)
        self.label_top_info_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_top_info_2.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.label_top_info_2.setFont(font)
        self.label_top_info_2.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_top_info_2.setText("")
        self.label_top_info_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_top_info_2.setObjectName("label_top_info_2")
        self.horizontalLayout_8.addWidget(self.label_top_info_2)
        self.verticalLayout_2.addWidget(self.frame_top_info)
        self.horizontalLayout_3.addWidget(self.frame_top_right)
        self.verticalLayout.addWidget(self.frame_top)
        self.frame_center = QtWidgets.QFrame(self.frame_main)
        self.frame_center.setStyleSheet("background-color: rgb(40, 44, 52);")
        self.frame_center.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_center.setObjectName("frame_center")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_center)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.frame_center)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_left_menu.sizePolicy().hasHeightForWidth())
        self.frame_left_menu.setSizePolicy(sizePolicy)
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_left_menu.setStyleSheet("background-color:rgb(52, 17, 0);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menus.setObjectName("frame_menus")
        self.layout_menus = QtWidgets.QVBoxLayout(self.frame_menus)
        self.layout_menus.setContentsMargins(0, 0, 0, 0)
        self.layout_menus.setSpacing(0)
        self.layout_menus.setObjectName("layout_menus")
        self.btn_home = QtWidgets.QPushButton(self.frame_menus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_home.sizePolicy().hasHeightForWidth())
        self.btn_home.setSizePolicy(sizePolicy)
        self.btn_home.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.btn_home.setFont(font)
        self.btn_home.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_home.setStyleSheet("QPushButton {    \n"
"    background-image: url(:/16x16/icons/16x16/cil-home.png);\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 28px solid rgb(52, 17, 0);\n"
"    background-color: rgb(52, 17, 0);\n"
"    text-align: left;\n"
"    padding-left: 45px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(24, 24, 24);\n"
"    border-left: 28px solid rgbrgb(24, 24, 24);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"    border-left: 28px solid rgb(85, 170, 255);\n"
"}")
        self.btn_home.setObjectName("btn_home")
        self.layout_menus.addWidget(self.btn_home)
        self.btn_satisPaneli = QtWidgets.QPushButton(self.frame_menus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_satisPaneli.sizePolicy().hasHeightForWidth())
        self.btn_satisPaneli.setSizePolicy(sizePolicy)
        self.btn_satisPaneli.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.btn_satisPaneli.setFont(font)
        self.btn_satisPaneli.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_satisPaneli.setStyleSheet("QPushButton {    \n"
"    background-image: url(:/16x16/icons/16x16/cil-transfer.png);\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 28px solid rgb(52, 17, 0);\n"
"    background-color: rgb(52, 17, 0);\n"
"    text-align: left;\n"
"    padding-left: 45px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(24, 24, 24);\n"
"    border-left: 28px solid rgbrgb(24, 24, 24);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"    border-left: 28px solid rgb(85, 170, 255);\n"
"}")
        self.btn_satisPaneli.setObjectName("btn_satisPaneli")
        self.layout_menus.addWidget(self.btn_satisPaneli)
        self.btn_stokPaneli = QtWidgets.QPushButton(self.frame_menus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_stokPaneli.sizePolicy().hasHeightForWidth())
        self.btn_stokPaneli.setSizePolicy(sizePolicy)
        self.btn_stokPaneli.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.btn_stokPaneli.setFont(font)
        self.btn_stokPaneli.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_stokPaneli.setStyleSheet("QPushButton {    \n"
"    background-image: url(:/16x16/icons/16x16/cil-devices.png);\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 28px solid rgb(52, 17, 0);\n"
"    background-color:rgb(52, 17, 0);\n"
"    text-align: left;\n"
"    padding-left: 45px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(24, 24, 24);\n"
"    border-left: 28px solid rgbrgb(24, 24, 24);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"    border-left: 28px solid rgb(85, 170, 255);\n"
"}")
        self.btn_stokPaneli.setObjectName("btn_stokPaneli")
        self.layout_menus.addWidget(self.btn_stokPaneli)
        self.verticalLayout_5.addWidget(self.frame_menus, 0, QtCore.Qt.AlignTop)
        self.frame_extra_menus = QtWidgets.QFrame(self.frame_left_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_extra_menus.sizePolicy().hasHeightForWidth())
        self.frame_extra_menus.setSizePolicy(sizePolicy)
        self.frame_extra_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_extra_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_extra_menus.setObjectName("frame_extra_menus")
        self.layout_menu_bottom = QtWidgets.QVBoxLayout(self.frame_extra_menus)
        self.layout_menu_bottom.setContentsMargins(0, 0, 0, 25)
        self.layout_menu_bottom.setSpacing(10)
        self.layout_menu_bottom.setObjectName("layout_menu_bottom")
        self.verticalLayout_5.addWidget(self.frame_extra_menus, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_content_right = QtWidgets.QFrame(self.frame_center)
        self.frame_content_right.setStyleSheet("background-color: rgb(44, 49, 60);")
        self.frame_content_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_content_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content_right.setObjectName("frame_content_right")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_content_right)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_content = QtWidgets.QFrame(self.frame_content_right)
        self.frame_content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_content)
        self.horizontalLayout_14.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_content)
        self.stackedWidget.setStyleSheet("background: transparent;")
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_hizliErisim = QtWidgets.QWidget()
        self.page_hizliErisim.setObjectName("page_hizliErisim")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_hizliErisim)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.fr_hizliErisim_ = QtWidgets.QFrame(self.page_hizliErisim)
        self.fr_hizliErisim_.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_hizliErisim_.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_hizliErisim_.setObjectName("fr_hizliErisim_")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.fr_hizliErisim_)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.txt_hizliE_barkod = QtWidgets.QLineEdit(self.fr_hizliErisim_)
        self.txt_hizliE_barkod.setMinimumSize(QtCore.QSize(300, 35))
        self.txt_hizliE_barkod.setMaximumSize(QtCore.QSize(600, 37))
        self.txt_hizliE_barkod.setStyleSheet("background-color: rgb(27, 29, 35);\n"
"\n"
"border-radius: 5px;\n"
"border-bottom: 1px solid rgb(44, 49, 60);\n"
"gridline-color:rgb(255, 170, 0);\n"
"font: 63 italic 11pt \"Segoe UI Semibold\";\n"
"")
        self.txt_hizliE_barkod.setObjectName("txt_hizliE_barkod")
        self.horizontalLayout_11.addWidget(self.txt_hizliE_barkod)
        self.btn_hizli_satisYap = QtWidgets.QPushButton(self.fr_hizliErisim_)
        self.btn_hizli_satisYap.setMinimumSize(QtCore.QSize(130, 30))
        self.btn_hizli_satisYap.setMaximumSize(QtCore.QSize(150, 35))
        self.btn_hizli_satisYap.setStyleSheet("QPushButton{\n"
"background-color: rgb(197, 197, 197);\n"
"color: #000;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 170, 127);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 220, 220);\n"
"}")
        self.btn_hizli_satisYap.setObjectName("btn_hizli_satisYap")
        self.horizontalLayout_11.addWidget(self.btn_hizli_satisYap)
        self.btn_hizli_iadeAl = QtWidgets.QPushButton(self.fr_hizliErisim_)
        self.btn_hizli_iadeAl.setMinimumSize(QtCore.QSize(135, 30))
        self.btn_hizli_iadeAl.setMaximumSize(QtCore.QSize(150, 35))
        self.btn_hizli_iadeAl.setStyleSheet("QPushButton{\n"
"background-color: rgb(197, 197, 197);\n"
"color: #000;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 170, 127);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 220, 220);\n"
"}")
        self.btn_hizli_iadeAl.setObjectName("btn_hizli_iadeAl")
        self.horizontalLayout_11.addWidget(self.btn_hizli_iadeAl)
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.verticalLayout_10.addWidget(self.fr_hizliErisim_)
        self.frame = QtWidgets.QFrame(self.page_hizliErisim)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_10.addWidget(self.frame)
        self.fr_hizliErisim_table = QtWidgets.QFrame(self.page_hizliErisim)
        self.fr_hizliErisim_table.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_hizliErisim_table.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_hizliErisim_table.setObjectName("fr_hizliErisim_table")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.fr_hizliErisim_table)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_2 = QtWidgets.QFrame(self.fr_hizliErisim_table)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_12 = QtWidgets.QFrame(self.frame_2)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 5)
        self.horizontalLayout_18.setSpacing(6)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.pushButton = QtWidgets.QPushButton(self.frame_12)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(197, 197, 197);\n"
"color: #000;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 170, 127);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 220, 220);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_18.addWidget(self.pushButton)
        self.txt_hizli_ara = QtWidgets.QLineEdit(self.frame_12)
        self.txt_hizli_ara.setMinimumSize(QtCore.QSize(300, 30))
        self.txt_hizli_ara.setMaximumSize(QtCore.QSize(300, 37))
        self.txt_hizli_ara.setStyleSheet("background-color: rgb(27, 29, 35);\n"
"border-radius: 5px;\n"
"border-bottom: 1px solid rgb(44, 49, 60);\n"
"gridline-color:rgb(255, 170, 0);\n"
"font: 63 italic 10pt \"Segoe USemibold\";\n"
"")
        self.txt_hizli_ara.setObjectName("txt_hizli_ara")
        self.horizontalLayout_18.addWidget(self.txt_hizli_ara)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem2)
        self.horizontalLayout_12.addWidget(self.frame_12)
        self.btn_hizliSil = QtWidgets.QPushButton(self.frame_2)
        self.btn_hizliSil.setMinimumSize(QtCore.QSize(40, 20))
        self.btn_hizliSil.setMaximumSize(QtCore.QSize(40, 20))
        self.btn_hizliSil.setStyleSheet("QPushButton{\n"
"background-color: rgb(76, 0, 0);\n"
"border-radius:10px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(24, 24, 24);\n"
"    \n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"\n"
"}")
        self.btn_hizliSil.setObjectName("btn_hizliSil")
        self.horizontalLayout_12.addWidget(self.btn_hizliSil)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.verticalLayout_7.addWidget(self.frame_2)
        self.tbl_hizliErisim = QtWidgets.QTableWidget(self.fr_hizliErisim_table)
        self.tbl_hizliErisim.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tbl_hizliErisim.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tbl_hizliErisim.setStyleSheet("QTableWidget {    \n"
"    background-color: rgb(39, 44, 54);\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    margin-top:20px;\n"
"}\n"
"QTableWidget::item{\n"
"    border-color: rgb(44, 49, 60);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"QHeaderView::section{\n"
"    Background-color: rgb(39, 44, 54);\n"
"    max-width: 30px;\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"    border-style: none;\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    border-right: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::horizontalHeader {    \n"
"    background-color: rgb(81, 255, 0);\n"
"}\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border: 1px solid rgb(32, 34, 42);\n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 3px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"}\n"
"")
        self.tbl_hizliErisim.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tbl_hizliErisim.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tbl_hizliErisim.setMidLineWidth(0)
        self.tbl_hizliErisim.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tbl_hizliErisim.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tbl_hizliErisim.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_hizliErisim.setProperty("showDropIndicator", True)
        self.tbl_hizliErisim.setDragDropOverwriteMode(True)
        self.tbl_hizliErisim.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbl_hizliErisim.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tbl_hizliErisim.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tbl_hizliErisim.setCornerButtonEnabled(True)
        self.tbl_hizliErisim.setObjectName("tbl_hizliErisim")
        self.tbl_hizliErisim.setColumnCount(0)
        self.tbl_hizliErisim.setRowCount(0)
        self.tbl_hizliErisim.horizontalHeader().setVisible(True)
        self.tbl_hizliErisim.horizontalHeader().setCascadingSectionResizes(True)
        self.tbl_hizliErisim.horizontalHeader().setDefaultSectionSize(200)
        self.tbl_hizliErisim.horizontalHeader().setHighlightSections(True)
        self.tbl_hizliErisim.horizontalHeader().setMinimumSectionSize(37)
        self.tbl_hizliErisim.horizontalHeader().setSortIndicatorShown(False)
        self.tbl_hizliErisim.horizontalHeader().setStretchLastSection(True)
        self.tbl_hizliErisim.verticalHeader().setVisible(False)
        self.tbl_hizliErisim.verticalHeader().setCascadingSectionResizes(False)
        self.tbl_hizliErisim.verticalHeader().setHighlightSections(False)
        self.tbl_hizliErisim.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_7.addWidget(self.tbl_hizliErisim)
        self.verticalLayout_10.addWidget(self.fr_hizliErisim_table)
        self.stackedWidget.addWidget(self.page_hizliErisim)
        self.page_stokPanel = QtWidgets.QWidget()
        self.page_stokPanel.setObjectName("page_stokPanel")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_stokPanel)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_3 = QtWidgets.QFrame(self.page_stokPanel)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_3)
        self.tabWidget.setMaximumSize(QtCore.QSize(900, 16777215))
        self.tabWidget.setSizeIncrement(QtCore.QSize(800, 0))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet("background-color: rgb(39, 44, 54);\n"
"gridline-color: rgb(44, 49, 60);\n"
"border-style:none;\n"
"\n"
"\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_urun_ekle = QtWidgets.QWidget()
        self.tab_urun_ekle.setStyleSheet("")
        self.tab_urun_ekle.setObjectName("tab_urun_ekle")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_urun_ekle)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_13 = QtWidgets.QFrame(self.tab_urun_ekle)
        self.frame_13.setStyleSheet("QFrame QLineEdit{\n"
"\n"
"background-color: rgb(27, 29, 35);\n"
"\n"
"border-radius: 5px;\n"
"border-bottom: 1px solid rgb(44, 49, 60);\n"
"gridline-color:rgb(255, 170, 0);\n"
"font: 63 italic 9pt \"Segoe UI Semibold\";\n"
"}\n"
"QDateTimeEdit{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QDateTimeEdit:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QDateTimeEdit QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(197, 197, 197);\n"
"color: #000;\n"
"border-radius:10px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 170, 127);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 220, 220);\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(3, -1, -1, 5)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.frame_13)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.ln_stokAdEkle = QtWidgets.QLineEdit(self.frame_13)
        self.ln_stokAdEkle.setMinimumSize(QtCore.QSize(0, 30))
        self.ln_stokAdEkle.setMaximumSize(QtCore.QSize(400, 35))
        self.ln_stokAdEkle.setObjectName("ln_stokAdEkle")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ln_stokAdEkle)
        self.ln_stokMarkaEkle = QtWidgets.QLineEdit(self.frame_13)
        self.ln_stokMarkaEkle.setMinimumSize(QtCore.QSize(0, 25))
        self.ln_stokMarkaEkle.setMaximumSize(QtCore.QSize(350, 35))
        self.ln_stokMarkaEkle.setObjectName("ln_stokMarkaEkle")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ln_stokMarkaEkle)
        self.ln_stokFiyatEkle = QtWidgets.QLineEdit(self.frame_13)
        self.ln_stokFiyatEkle.setMinimumSize(QtCore.QSize(0, 25))
        self.ln_stokFiyatEkle.setMaximumSize(QtCore.QSize(100, 25))
        self.ln_stokFiyatEkle.setSizeIncrement(QtCore.QSize(0, 30))
        self.ln_stokFiyatEkle.setObjectName("ln_stokFiyatEkle")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ln_stokFiyatEkle)
        self.sp_stokAdetEkle = QtWidgets.QSpinBox(self.frame_13)
        self.sp_stokAdetEkle.setStyleSheet("QSpinBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QSpinBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QSpinBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.sp_stokAdetEkle.setObjectName("sp_stokAdetEkle")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.sp_stokAdetEkle)
        self.label_5 = QtWidgets.QLabel(self.frame_13)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.frame_13)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.frame_13)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_9 = QtWidgets.QLabel(self.frame_13)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_8 = QtWidgets.QLabel(self.frame_13)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.date_stok = QtWidgets.QDateTimeEdit(self.frame_13)
        self.date_stok.setEnabled(False)
        self.date_stok.setObjectName("date_stok")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.date_stok)
        self.label_10 = QtWidgets.QLabel(self.frame_13)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.ln_stokBarkodEkle = QtWidgets.QLineEdit(self.frame_13)
        self.ln_stokBarkodEkle.setMinimumSize(QtCore.QSize(0, 25))
        self.ln_stokBarkodEkle.setMaximumSize(QtCore.QSize(350, 35))
        self.ln_stokBarkodEkle.setObjectName("ln_stokBarkodEkle")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.ln_stokBarkodEkle)
        self.btn_stokKaydiTamamla = QtWidgets.QPushButton(self.frame_13)
        self.btn_stokKaydiTamamla.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_stokKaydiTamamla.setMaximumSize(QtCore.QSize(150, 25))
        self.btn_stokKaydiTamamla.setObjectName("btn_stokKaydiTamamla")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.btn_stokKaydiTamamla)
        self.label_21 = QtWidgets.QLabel(self.frame_13)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.label_21)
        self.verticalLayout_14.addLayout(self.formLayout)
        self.verticalLayout_9.addWidget(self.frame_13)
        self.tabWidget.addTab(self.tab_urun_ekle, "")
        self.tab_urun_sil = QtWidgets.QWidget()
        self.tab_urun_sil.setObjectName("tab_urun_sil")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.tab_urun_sil)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_14 = QtWidgets.QFrame(self.tab_urun_sil)
        self.frame_14.setStyleSheet("QFrame QLineEdit{\n"
"\n"
"background-color: rgb(27, 29, 35);\n"
"\n"
"border-radius: 5px;\n"
"border-bottom: 1px solid rgb(44, 49, 60);\n"
"gridline-color:rgb(255, 170, 0);\n"
"font: 63 italic 9pt \"Segoe UI Semibold\";\n"
"}\n"
"QDateTimeEdit{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QDateTimeEdit:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QDateTimeEdit QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(197, 197, 197);\n"
"color: #000;\n"
"border-radius:10px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 170, 127);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 220, 220);\n"
"}")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(3, -1, -1, 5)
        self.formLayout_2.setVerticalSpacing(10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_11 = QtWidgets.QLabel(self.frame_14)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.ln_stokSil = QtWidgets.QLineEdit(self.frame_14)
        self.ln_stokSil.setMinimumSize(QtCore.QSize(0, 30))
        self.ln_stokSil.setMaximumSize(QtCore.QSize(400, 35))
        self.ln_stokSil.setObjectName("ln_stokSil")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ln_stokSil)
        self.label_12 = QtWidgets.QLabel(self.frame_14)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.ln_stokSilAd = QtWidgets.QLineEdit(self.frame_14)
        self.ln_stokSilAd.setMinimumSize(QtCore.QSize(0, 25))
        self.ln_stokSilAd.setMaximumSize(QtCore.QSize(350, 35))
        self.ln_stokSilAd.setObjectName("ln_stokSilAd")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ln_stokSilAd)
        self.label_14 = QtWidgets.QLabel(self.frame_14)
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.btn_stokUrunSil = QtWidgets.QPushButton(self.frame_14)
        self.btn_stokUrunSil.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_stokUrunSil.setMaximumSize(QtCore.QSize(150, 25))
        self.btn_stokUrunSil.setObjectName("btn_stokUrunSil")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.btn_stokUrunSil)
        self.label_13 = QtWidgets.QLabel(self.frame_14)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_13)
        self.verticalLayout_16.addLayout(self.formLayout_2)
        self.verticalLayout_15.addWidget(self.frame_14)
        self.tabWidget.addTab(self.tab_urun_sil, "")
        self.tab_urun_guncelle = QtWidgets.QWidget()
        self.tab_urun_guncelle.setObjectName("tab_urun_guncelle")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.tab_urun_guncelle)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_15 = QtWidgets.QFrame(self.tab_urun_guncelle)
        self.frame_15.setStyleSheet("QFrame QLineEdit{\n"
"\n"
"background-color: rgb(27, 29, 35);\n"
"\n"
"border-radius: 5px;\n"
"border-bottom: 1px solid rgb(44, 49, 60);\n"
"gridline-color:rgb(255, 170, 0);\n"
"font: 63 italic 9pt \"Segoe UI Semibold\";\n"
"}\n"
"QDateTimeEdit{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QDateTimeEdit:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QDateTimeEdit QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(197, 197, 197);\n"
"color: #000;\n"
"border-radius:10px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 170, 127);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 220, 220);\n"
"}\n"
"QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_18.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_3.setContentsMargins(5, -1, -1, 5)
        self.formLayout_3.setHorizontalSpacing(5)
        self.formLayout_3.setVerticalSpacing(10)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_15 = QtWidgets.QLabel(self.frame_15)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.ln_stokGuncelleAd = QtWidgets.QLineEdit(self.frame_15)
        self.ln_stokGuncelleAd.setMinimumSize(QtCore.QSize(0, 30))
        self.ln_stokGuncelleAd.setMaximumSize(QtCore.QSize(400, 35))
        self.ln_stokGuncelleAd.setObjectName("ln_stokGuncelleAd")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ln_stokGuncelleAd)
        self.label_16 = QtWidgets.QLabel(self.frame_15)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.label_17 = QtWidgets.QLabel(self.frame_15)
        self.label_17.setObjectName("label_17")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_20 = QtWidgets.QLabel(self.frame_15)
        self.label_20.setObjectName("label_20")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.date_stokGuncelTime = QtWidgets.QDateTimeEdit(self.frame_15)
        self.date_stokGuncelTime.setEnabled(False)
        self.date_stokGuncelTime.setObjectName("date_stokGuncelTime")
        self.formLayout_3.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.date_stokGuncelTime)
        self.label_18 = QtWidgets.QLabel(self.frame_15)
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.formLayout_3.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.btn_stokUrunGuncelle = QtWidgets.QPushButton(self.frame_15)
        self.btn_stokUrunGuncelle.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_stokUrunGuncelle.setMaximumSize(QtCore.QSize(150, 25))
        self.btn_stokUrunGuncelle.setObjectName("btn_stokUrunGuncelle")
        self.formLayout_3.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.btn_stokUrunGuncelle)
        self.ln_stokYeniBilgi = QtWidgets.QLineEdit(self.frame_15)
        self.ln_stokYeniBilgi.setMinimumSize(QtCore.QSize(0, 35))
        self.ln_stokYeniBilgi.setMaximumSize(QtCore.QSize(350, 35))
        self.ln_stokYeniBilgi.setObjectName("ln_stokYeniBilgi")
        self.formLayout_3.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.ln_stokYeniBilgi)
        self.cmb_guncellenecekBilgi = QtWidgets.QComboBox(self.frame_15)
        self.cmb_guncellenecekBilgi.setMinimumSize(QtCore.QSize(200, 30))
        self.cmb_guncellenecekBilgi.setMaximumSize(QtCore.QSize(200, 16777215))
        self.cmb_guncellenecekBilgi.setObjectName("cmb_guncellenecekBilgi")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cmb_guncellenecekBilgi)
        self.label_22 = QtWidgets.QLabel(self.frame_15)
        self.label_22.setObjectName("label_22")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_22)
        self.label_23 = QtWidgets.QLabel(self.frame_15)
        self.label_23.setObjectName("label_23")
        self.formLayout_3.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.label_23)
        self.verticalLayout_18.addLayout(self.formLayout_3)
        self.verticalLayout_17.addWidget(self.frame_15)
        self.tabWidget.addTab(self.tab_urun_guncelle, "")
        self.horizontalLayout_13.addWidget(self.tabWidget)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem4)
        self.verticalLayout_6.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.page_stokPanel)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.tbl_stok = QtWidgets.QTableWidget(self.frame_4)
        self.tbl_stok.setStyleSheet("QTableWidget {    \n"
"    background-color: rgb(39, 44, 54);\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    margin-top:20px;\n"
"}\n"
"QTableWidget::item{\n"
"    border-color: rgb(44, 49, 60);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"QHeaderView::section{\n"
"    Background-color: rgb(39, 44, 54);\n"
"    max-width: 30px;\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"    border-style: none;\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    border-right: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::horizontalHeader {    \n"
"    background-color: rgb(81, 255, 0);\n"
"}\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border: 1px solid rgb(32, 34, 42);\n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 3px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"}\n"
"")
        self.tbl_stok.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tbl_stok.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tbl_stok.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tbl_stok.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tbl_stok.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_stok.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbl_stok.setCornerButtonEnabled(True)
        self.tbl_stok.setObjectName("tbl_stok")
        self.tbl_stok.setColumnCount(0)
        self.tbl_stok.setRowCount(0)
        self.tbl_stok.horizontalHeader().setCascadingSectionResizes(True)
        self.tbl_stok.horizontalHeader().setDefaultSectionSize(200)
        self.tbl_stok.horizontalHeader().setHighlightSections(True)
        self.tbl_stok.horizontalHeader().setSortIndicatorShown(False)
        self.tbl_stok.horizontalHeader().setStretchLastSection(True)
        self.tbl_stok.verticalHeader().setVisible(False)
        self.tbl_stok.verticalHeader().setCascadingSectionResizes(False)
        self.tbl_stok.verticalHeader().setHighlightSections(False)
        self.tbl_stok.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_11.addWidget(self.tbl_stok)
        self.verticalLayout_6.addWidget(self.frame_4)
        self.stackedWidget.addWidget(self.page_stokPanel)
        self.page_kullaniciAyar = QtWidgets.QWidget()
        self.page_kullaniciAyar.setObjectName("page_kullaniciAyar")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.page_kullaniciAyar)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_16 = QtWidgets.QFrame(self.page_kullaniciAyar)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem5)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(5, 150, -1, -1)
        self.gridLayout_4.setVerticalSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_26 = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 1, 0, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.frame_16)
        self.toolButton.setStyleSheet("QToolButton{\n"
"background-color: rgb(197, 197, 197);\n"
"color: #000;\n"
"border-radius:10px;\n"
"\n"
"}\n"
"QToolButtonn:hover{\n"
"background-color: rgb(85, 170, 127);\n"
"\n"
"}\n"
"QToolButton:pressed{\n"
"background-color: rgb(0, 220, 220);\n"
"}")
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_4.addWidget(self.toolButton, 1, 2, 1, 1)
        self.ln_dbAdres = QtWidgets.QLineEdit(self.frame_16)
        self.ln_dbAdres.setMinimumSize(QtCore.QSize(300, 30))
        self.ln_dbAdres.setMaximumSize(QtCore.QSize(300, 30))
        self.ln_dbAdres.setStyleSheet("background-color: rgb(27, 29, 35);\n"
"\n"
"border-radius: 5px;\n"
"border-bottom: 1px solid rgb(44, 49, 60);\n"
"gridline-color:rgb(255, 170, 0);\n"
"font: 63 italic 11pt \"Segoe UI Semibold\";\n"
"")
        self.ln_dbAdres.setObjectName("ln_dbAdres")
        self.gridLayout_4.addWidget(self.ln_dbAdres, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 0, 0, 1, 1)
        self.ln_token = QtWidgets.QLineEdit(self.frame_16)
        self.ln_token.setMinimumSize(QtCore.QSize(300, 30))
        self.ln_token.setMaximumSize(QtCore.QSize(300, 30))
        self.ln_token.setStyleSheet("background-color: rgb(27, 29, 35);\n"
"\n"
"border-radius: 5px;\n"
"border-bottom: 1px solid rgb(44, 49, 60);\n"
"gridline-color:rgb(255, 170, 0);\n"
"font: 63 italic 11pt \"Segoe UI Semibold\";\n"
"")
        self.ln_token.setObjectName("ln_token")
        self.gridLayout_4.addWidget(self.ln_token, 1, 1, 1, 1)
        self.btn_dbBaglan = QtWidgets.QPushButton(self.frame_16)
        self.btn_dbBaglan.setMinimumSize(QtCore.QSize(125, 30))
        self.btn_dbBaglan.setMaximumSize(QtCore.QSize(125, 30))
        self.btn_dbBaglan.setStyleSheet("QPushButton{\n"
"background-color: rgb(197, 197, 197);\n"
"color: #000;\n"
"border-radius:10px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 170, 127);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 220, 220);\n"
"}")
        self.btn_dbBaglan.setObjectName("btn_dbBaglan")
        self.gridLayout_4.addWidget(self.btn_dbBaglan, 4, 1, 1, 1)
        self.listView = QtWidgets.QListView(self.frame_16)
        self.listView.setMinimumSize(QtCore.QSize(0, 200))
        self.listView.setMaximumSize(QtCore.QSize(16777215, 350))
        self.listView.setSizeIncrement(QtCore.QSize(0, 200))
        self.listView.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.listView.setObjectName("listView")
        self.gridLayout_4.addWidget(self.listView, 3, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 2, 0, 1, 1)
        self.horizontalLayout_19.addLayout(self.gridLayout_4)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem6)
        self.verticalLayout_19.addWidget(self.frame_16)
        self.stackedWidget.addWidget(self.page_kullaniciAyar)
        self.page_satisPanel = QtWidgets.QWidget()
        self.page_satisPanel.setObjectName("page_satisPanel")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_satisPanel)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.fr_satisSol = QtWidgets.QFrame(self.page_satisPanel)
        self.fr_satisSol.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_satisSol.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_satisSol.setObjectName("fr_satisSol")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.fr_satisSol)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_7 = QtWidgets.QFrame(self.fr_satisSol)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_17.setContentsMargins(80, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(6)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem7)
        self.ln_fiyat_goster = QtWidgets.QLineEdit(self.frame_8)
        self.ln_fiyat_goster.setMaximumSize(QtCore.QSize(400, 50))
        self.ln_fiyat_goster.setToolTip("")
        self.ln_fiyat_goster.setToolTipDuration(1)
        self.ln_fiyat_goster.setStatusTip("")
        self.ln_fiyat_goster.setAccessibleDescription("")
        self.ln_fiyat_goster.setStyleSheet("background-color: rgb(27, 29, 35);\n"
"padding: 10px;\n"
"border-radius: 5px;\n"
"border-bottom: 1px solid rgb(44, 49, 60);\n"
"gridline-color: rgb(44, 49, 60);\n"
"font: 12pt \"MS Serif\";")
        self.ln_fiyat_goster.setFrame(True)
        self.ln_fiyat_goster.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ln_fiyat_goster.setObjectName("ln_fiyat_goster")
        self.horizontalLayout_17.addWidget(self.ln_fiyat_goster)
        self.btn_satis_temizle = QtWidgets.QPushButton(self.frame_8)
        self.btn_satis_temizle.setMaximumSize(QtCore.QSize(150, 50))
        self.btn_satis_temizle.setStyleSheet("QPushButton{\n"
"background-color: rgb(197, 197, 197);\n"
"color: #000;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 170, 127);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 220, 220);\n"
"}")
        self.btn_satis_temizle.setObjectName("btn_satis_temizle")
        self.horizontalLayout_17.addWidget(self.btn_satis_temizle)
        self.gridLayout_2.addWidget(self.frame_8, 0, 1, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame_7)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout.setContentsMargins(25, 5, 10, 0)
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setVerticalSpacing(40)
        self.gridLayout.setObjectName("gridLayout")
        self.ln_satis_barkod = QtWidgets.QLineEdit(self.frame_5)
        self.ln_satis_barkod.setMinimumSize(QtCore.QSize(200, 35))
        self.ln_satis_barkod.setMaximumSize(QtCore.QSize(400, 40))
        self.ln_satis_barkod.setSizeIncrement(QtCore.QSize(0, 0))
        self.ln_satis_barkod.setStyleSheet("background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    gridline-color: rgb(44, 49, 60);")
        self.ln_satis_barkod.setObjectName("ln_satis_barkod")
        self.gridLayout.addWidget(self.ln_satis_barkod, 0, 1, 1, 3)
        self.cmb_indirim = QtWidgets.QComboBox(self.frame_5)
        self.cmb_indirim.setStyleSheet("QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.cmb_indirim.setObjectName("cmb_indirim")
        self.cmb_indirim.addItem("")
        self.cmb_indirim.addItem("")
        self.cmb_indirim.addItem("")
        self.cmb_indirim.addItem("")
        self.cmb_indirim.addItem("")
        self.gridLayout.addWidget(self.cmb_indirim, 1, 2, 1, 1)
        self.spin_adet = QtWidgets.QSpinBox(self.frame_5)
        self.spin_adet.setStyleSheet("QSpinBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QSpinBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QSpinBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.spin_adet.setObjectName("spin_adet")
        self.gridLayout.addWidget(self.spin_adet, 1, 0, 1, 1)
        self.date_satis = QtWidgets.QDateTimeEdit(self.frame_5)
        self.date_satis.setEnabled(False)
        self.date_satis.setStyleSheet("QDateTimeEdit{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QDateTimeEdit:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QDateTimeEdit QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.date_satis.setObjectName("date_satis")
        self.gridLayout.addWidget(self.date_satis, 1, 3, 1, 1)
        self.btn_satis_diger = QtWidgets.QPushButton(self.frame_5)
        self.btn_satis_diger.setMaximumSize(QtCore.QSize(150, 50))
        self.btn_satis_diger.setStyleSheet("QPushButton{\n"
"background-color: rgb(197, 197, 197);\n"
"color: #000;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 170, 127);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 220, 220);\n"
"}")
        self.btn_satis_diger.setObjectName("btn_satis_diger")
        self.gridLayout.addWidget(self.btn_satis_diger, 0, 0, 1, 1)
        self.btn_satisEkle = QtWidgets.QPushButton(self.frame_5)
        self.btn_satisEkle.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 104, 0);\n"
"color: #fff;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(170, 170, 255);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 220, 220);\n"
"}")
        self.btn_satisEkle.setObjectName("btn_satisEkle")
        self.gridLayout.addWidget(self.btn_satisEkle, 1, 4, 1, 1)
        self.gridLayout_2.addWidget(self.frame_5, 0, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.frame_7)
        self.verticalLayout_12.addWidget(self.fr_satisSol)
        self.fr_satisSag = QtWidgets.QFrame(self.page_satisPanel)
        self.fr_satisSag.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_satisSag.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_satisSag.setObjectName("fr_satisSag")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.fr_satisSag)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_6 = QtWidgets.QFrame(self.fr_satisSag)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.frame_9 = QtWidgets.QFrame(self.frame_6)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.tbl_satis_listele = QtWidgets.QTableWidget(self.frame_9)
        self.tbl_satis_listele.setMinimumSize(QtCore.QSize(400, 300))
        self.tbl_satis_listele.setMaximumSize(QtCore.QSize(600, 350))
        self.tbl_satis_listele.setStyleSheet("QTableWidget {    \n"
"    background-color: rgb(39, 44, 54);\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    margin-top:20px;\n"
"}\n"
"QTableWidget::item{\n"
"    border-color: rgb(44, 49, 60);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"QHeaderView::section{\n"
"    Background-color: rgb(39, 44, 54);\n"
"    max-width: 30px;\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"    border-style: none;\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    border-right: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::horizontalHeader {    \n"
"    background-color: rgb(81, 255, 0);\n"
"}\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border: 1px solid rgb(32, 34, 42);\n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 3px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"}\n"
"")
        self.tbl_satis_listele.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tbl_satis_listele.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tbl_satis_listele.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tbl_satis_listele.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tbl_satis_listele.setAutoScroll(True)
        self.tbl_satis_listele.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_satis_listele.setDragEnabled(False)
        self.tbl_satis_listele.setAlternatingRowColors(False)
        self.tbl_satis_listele.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbl_satis_listele.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tbl_satis_listele.setShowGrid(True)
        self.tbl_satis_listele.setObjectName("tbl_satis_listele")
        self.tbl_satis_listele.setColumnCount(4)
        self.tbl_satis_listele.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_satis_listele.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_satis_listele.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_satis_listele.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_satis_listele.setHorizontalHeaderItem(3, item)
        self.tbl_satis_listele.horizontalHeader().setCascadingSectionResizes(True)
        self.tbl_satis_listele.horizontalHeader().setDefaultSectionSize(200)
        self.tbl_satis_listele.horizontalHeader().setHighlightSections(True)
        self.tbl_satis_listele.horizontalHeader().setStretchLastSection(True)
        self.tbl_satis_listele.verticalHeader().setVisible(False)
        self.tbl_satis_listele.verticalHeader().setHighlightSections(False)
        self.tbl_satis_listele.verticalHeader().setSortIndicatorShown(False)
        self.tbl_satis_listele.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_13.addWidget(self.tbl_satis_listele)
        self.horizontalLayout_16.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_6)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.list_satis_goster = QtWidgets.QListWidget(self.frame_10)
        self.list_satis_goster.setMinimumSize(QtCore.QSize(400, 300))
        self.list_satis_goster.setMaximumSize(QtCore.QSize(500, 350))
        self.list_satis_goster.setStyleSheet("    background-color: rgb(39, 44, 54);\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    gridline-color: rgb(44, 49, 60);")
        self.list_satis_goster.setObjectName("list_satis_goster")
        self.gridLayout_3.addWidget(self.list_satis_goster, 1, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem8, 3, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 1, 0, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label = QtWidgets.QLabel(self.frame_11)
        self.label.setObjectName("label")
        self.horizontalLayout_15.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.frame_11)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_15.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.frame_11)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_15.addWidget(self.label_2)
        self.label_19 = QtWidgets.QLabel(self.frame_11)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_15.addWidget(self.label_19)
        self.gridLayout_3.addWidget(self.frame_11, 0, 1, 1, 1)
        self.btn_satisTamam = QtWidgets.QPushButton(self.frame_10)
        self.btn_satisTamam.setMinimumSize(QtCore.QSize(250, 35))
        self.btn_satisTamam.setMaximumSize(QtCore.QSize(250, 35))
        self.btn_satisTamam.setStyleSheet("QPushButton{\n"
"background-color: rgb(29, 29, 29);\n"
"color: #fff;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(85, 170, 127);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 220, 220);\n"
"}")
        self.btn_satisTamam.setObjectName("btn_satisTamam")
        self.gridLayout_3.addWidget(self.btn_satisTamam, 2, 1, 1, 1)
        self.horizontalLayout_16.addWidget(self.frame_10)
        self.verticalLayout_8.addWidget(self.frame_6)
        self.verticalLayout_12.addWidget(self.fr_satisSag)
        self.stackedWidget.addWidget(self.page_satisPanel)
        self.horizontalLayout_14.addWidget(self.stackedWidget)
        self.verticalLayout_4.addWidget(self.frame_content)
        self.frame_grip = QtWidgets.QFrame(self.frame_content_right)
        self.frame_grip.setMinimumSize(QtCore.QSize(0, 25))
        self.frame_grip.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_grip.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.frame_grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_grip)
        self.horizontalLayout_6.setContentsMargins(0, 0, 2, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_label_bottom = QtWidgets.QFrame(self.frame_grip)
        self.frame_label_bottom.setStyleSheet("background-color: rgb(29, 29, 29);")
        self.frame_label_bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_label_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_bottom.setObjectName("frame_label_bottom")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_label_bottom)
        self.horizontalLayout_7.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_credits = QtWidgets.QLabel(self.frame_label_bottom)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color: rgb(98, 103, 111);\n"
"background-color: rgb(29, 29, 29);")
        self.label_credits.setObjectName("label_credits")
        self.horizontalLayout_7.addWidget(self.label_credits)
        self.label_version = QtWidgets.QLabel(self.frame_label_bottom)
        self.label_version.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_version.setFont(font)
        self.label_version.setStyleSheet("color: rgb(98, 103, 111);\n"
"background-color: rgb(29, 29, 29);")
        self.label_version.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_version.setObjectName("label_version")
        self.horizontalLayout_7.addWidget(self.label_version)
        self.horizontalLayout_6.addWidget(self.frame_label_bottom)
        self.verticalLayout_4.addWidget(self.frame_grip)
        self.horizontalLayout_2.addWidget(self.frame_content_right)
        self.verticalLayout.addWidget(self.frame_center)
        self.horizontalLayout.addWidget(self.frame_main)
        AnaSayfa_.setCentralWidget(self.centralwidget)

        self.retranslateUi(AnaSayfa_)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(AnaSayfa_)

    def retranslateUi(self, AnaSayfa_):
        _translate = QtCore.QCoreApplication.translate
        AnaSayfa_.setWindowTitle(_translate("AnaSayfa_", "MainWindow"))
        self.btn_settings.setText(_translate("AnaSayfa_", "Open File"))
        self.label_title_bar_top.setText(_translate("AnaSayfa_", "Hogg Panel"))
        self.btn_minimize.setToolTip(_translate("AnaSayfa_", "Minimize"))
        self.btn_maximize_restore.setToolTip(_translate("AnaSayfa_", "Maximize"))
        self.btn_close.setToolTip(_translate("AnaSayfa_", "Close"))
        self.label_top_info.setText(_translate("AnaSayfa_", "Buradan ürünlerinizin satışını hızlıca yapabilir ve güncelleyebilirsiniz.."))
        self.btn_home.setText(_translate("AnaSayfa_", "Save"))
        self.btn_satisPaneli.setText(_translate("AnaSayfa_", "New"))
        self.btn_stokPaneli.setText(_translate("AnaSayfa_", "New User"))
        self.txt_hizliE_barkod.setPlaceholderText(_translate("AnaSayfa_", "Barkod veya Ürün adı Gir"))
        self.btn_hizli_satisYap.setText(_translate("AnaSayfa_", "Satış Yap"))
        self.btn_hizli_iadeAl.setText(_translate("AnaSayfa_", "İade Al"))
        self.pushButton.setText(_translate("AnaSayfa_", "Ara"))
        self.txt_hizli_ara.setPlaceholderText(_translate("AnaSayfa_", "Arama yap"))
        self.btn_hizliSil.setText(_translate("AnaSayfa_", "-"))
        self.tbl_hizliErisim.setSortingEnabled(False)
        self.label_4.setText(_translate("AnaSayfa_", "Ürün Adı"))
        self.ln_stokAdEkle.setPlaceholderText(_translate("AnaSayfa_", "Ürün adı gir"))
        self.ln_stokMarkaEkle.setPlaceholderText(_translate("AnaSayfa_", "Marka gir"))
        self.ln_stokFiyatEkle.setPlaceholderText(_translate("AnaSayfa_", "Fiyat gir"))
        self.label_5.setText(_translate("AnaSayfa_", "Marka"))
        self.label_6.setText(_translate("AnaSayfa_", "Fiyat"))
        self.label_9.setText(_translate("AnaSayfa_", "Adet"))
        self.label_8.setText(_translate("AnaSayfa_", "Tarih"))
        self.label_10.setText(_translate("AnaSayfa_", "Barkod"))
        self.ln_stokBarkodEkle.setPlaceholderText(_translate("AnaSayfa_", "Barkod gir"))
        self.btn_stokKaydiTamamla.setText(_translate("AnaSayfa_", "Kaydı Tamamla"))
        self.label_21.setText(_translate("AnaSayfa_", "Tarih bilgisi otomatik olarak belirlenir."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_urun_ekle), _translate("AnaSayfa_", "Ürün Ekle"))
        self.label_11.setText(_translate("AnaSayfa_", "Barkod"))
        self.ln_stokSil.setPlaceholderText(_translate("AnaSayfa_", "Ürün adı veya barkod gir"))
        self.label_12.setText(_translate("AnaSayfa_", "Ürün adı"))
        self.ln_stokSilAd.setPlaceholderText(_translate("AnaSayfa_", "Ayrıca ürün adı da verebilirsin"))
        self.btn_stokUrunSil.setText(_translate("AnaSayfa_", "Ürünü Sil"))
        self.label_13.setText(_translate("AnaSayfa_", "Buradan yapılan işlemler ürünü stoktan kalıcı olarak silecektir. Eğer farklı bir işlem istiyorsnız güncelle sekmesine göz atın."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_urun_sil), _translate("AnaSayfa_", "Ürün Sil"))
        self.label_15.setText(_translate("AnaSayfa_", "Güncellenecek Ürün Bilgisi"))
        self.ln_stokGuncelleAd.setPlaceholderText(_translate("AnaSayfa_", "Barkod veya ürün adı gir"))
        self.label_16.setText(_translate("AnaSayfa_", "Neyi Güncelleyeceksiniz"))
        self.label_17.setText(_translate("AnaSayfa_", "Yeni Bilgi"))
        self.label_20.setText(_translate("AnaSayfa_", "Güncellenme Tarihi"))
        self.btn_stokUrunGuncelle.setText(_translate("AnaSayfa_", "Ürün Güncelle"))
        self.ln_stokYeniBilgi.setPlaceholderText(_translate("AnaSayfa_", "Güncellenecek yeni bilgi"))
        self.label_22.setText(_translate("AnaSayfa_", "Güncellenecek ürün bilgisini belirtin"))
        self.label_23.setText(_translate("AnaSayfa_", "Tarih otomatik olarak atanır."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_urun_guncelle), _translate("AnaSayfa_", "Ürün Güncelle"))
        self.label_26.setText(_translate("AnaSayfa_", "Token Bilgisi"))
        self.toolButton.setText(_translate("AnaSayfa_", "Browse.."))
        self.label_24.setText(_translate("AnaSayfa_", "Veritaban Link"))
        self.btn_dbBaglan.setText(_translate("AnaSayfa_", "Bağlan"))
        self.label_27.setText(_translate("AnaSayfa_", "Bilgiler"))
        self.ln_fiyat_goster.setWhatsThis(_translate("AnaSayfa_", "<html><head/><body><p><span style=\" color:#550000;\">fiyat bilgisi</span></p></body></html>"))
        self.ln_fiyat_goster.setPlaceholderText(_translate("AnaSayfa_", "Fiyat Bilgisi"))
        self.btn_satis_temizle.setText(_translate("AnaSayfa_", "Temizle"))
        self.ln_satis_barkod.setPlaceholderText(_translate("AnaSayfa_", "Barkod numarası gir"))
        self.cmb_indirim.setItemText(0, _translate("AnaSayfa_", "%5 İndirim"))
        self.cmb_indirim.setItemText(1, _translate("AnaSayfa_", "%10 İndirim"))
        self.cmb_indirim.setItemText(2, _translate("AnaSayfa_", "%20 İndirim"))
        self.cmb_indirim.setItemText(3, _translate("AnaSayfa_", "%25 İndirim"))
        self.cmb_indirim.setItemText(4, _translate("AnaSayfa_", "%50 İndirim"))
        self.btn_satis_diger.setText(_translate("AnaSayfa_", "Diğer (F5)"))
        self.btn_satisEkle.setText(_translate("AnaSayfa_", "Ekle"))
        item = self.tbl_satis_listele.horizontalHeaderItem(0)
        item.setText(_translate("AnaSayfa_", "Ürün Adı"))
        item = self.tbl_satis_listele.horizontalHeaderItem(1)
        item.setText(_translate("AnaSayfa_", "Adet"))
        item = self.tbl_satis_listele.horizontalHeaderItem(2)
        item.setText(_translate("AnaSayfa_", "Fiyat"))
        item = self.tbl_satis_listele.horizontalHeaderItem(3)
        item.setText(_translate("AnaSayfa_", "İndirim Oranı"))
        self.label.setText(_translate("AnaSayfa_", "Ürün Adı"))
        self.label_3.setText(_translate("AnaSayfa_", "Adedi"))
        self.label_2.setText(_translate("AnaSayfa_", "Fiyatı"))
        self.label_19.setText(_translate("AnaSayfa_", "İndirim Oranı"))
        self.btn_satisTamam.setText(_translate("AnaSayfa_", "Satışı Tamamla"))
        self.label_credits.setText(_translate("AnaSayfa_", "Redit By: Hasan Güneş & Onur Gürler"))
        self.label_version.setText(_translate("AnaSayfa_", "v1.0"))
import files_rc
