# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_splash.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SplashWindow(object):
    def setupUi(self, SplashWindow):
        SplashWindow.setObjectName("SplashWindow")
        SplashWindow.resize(620, 311)
        self.centralwidget = QtWidgets.QWidget(SplashWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        self.dropShadowFrame.setStyleSheet("QFrame{\n"
"background-color: rgb(25, 10, 58);\n"
"color: rgb(220, 220, 220);\n"
"border-radius: 10px;\n"
"border-style: none; \n"
"}")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.lbl_spTitle = QtWidgets.QLabel(self.dropShadowFrame)
        self.lbl_spTitle.setGeometry(QtCore.QRect(0, 70, 611, 81))
        font = QtGui.QFont()
        font.setFamily("Meiryo")
        font.setPointSize(25)
        self.lbl_spTitle.setFont(font)
        self.lbl_spTitle.setStyleSheet("color: rgb(193, 72, 171);")
        self.lbl_spTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_spTitle.setObjectName("lbl_spTitle")
        self.lbl_spTitle_2 = QtWidgets.QLabel(self.dropShadowFrame)
        self.lbl_spTitle_2.setGeometry(QtCore.QRect(20, 140, 561, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        self.lbl_spTitle_2.setFont(font)
        self.lbl_spTitle_2.setStyleSheet("color:rgb(213, 213, 213);")
        self.lbl_spTitle_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_spTitle_2.setObjectName("lbl_spTitle_2")
        self.progressBar = QtWidgets.QProgressBar(self.dropShadowFrame)
        self.progressBar.setGeometry(QtCore.QRect(20, 220, 561, 20))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"background-color: rgb(98,114,164);\n"
"color: rgb(200,200,200);\n"
"border-radius: 10px;\n"
"text-align:center;\n"
"border-style: none;\n"
"}\n"
"QProgressBar::chunk{\n"
"background-color:qlineargradient(spread:pad, x1:0.193182, y1:0.438, x2:1, y2:0, stop:0 rgba(188, 255, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
"border-radius: 10px;\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(self.dropShadowFrame)
        self.label.setGeometry(QtCore.QRect(280, 250, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.lbl_credits = QtWidgets.QLabel(self.dropShadowFrame)
        self.lbl_credits.setGeometry(QtCore.QRect(30, 10, 561, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei Light")
        font.setPointSize(10)
        self.lbl_credits.setFont(font)
        self.lbl_credits.setStyleSheet("color:rgb(213, 213, 213);")
        self.lbl_credits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_credits.setObjectName("lbl_credits")
        self.verticalLayout.addWidget(self.dropShadowFrame)
        SplashWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SplashWindow)
        QtCore.QMetaObject.connectSlotsByName(SplashWindow)

    def retranslateUi(self, SplashWindow):
        _translate = QtCore.QCoreApplication.translate
        SplashWindow.setWindowTitle(_translate("SplashWindow", "MainWindow"))
        self.lbl_spTitle.setText(_translate("SplashWindow", "<html><head/><body><p><span style=\" font-weight:600;\">WELCOME</span> HOGG <span style=\" color:#fefefe;\">SOFTWARE</span></p></body></html>"))
        self.lbl_spTitle_2.setText(_translate("SplashWindow", "<html><head/><body><p>Yönetimde tek yol Hogg...</p></body></html>"))
        self.label.setText(_translate("SplashWindow", "yükleniyor.."))
        self.lbl_credits.setText(_translate("SplashWindow", "<html><head/><body><p><span style=\" font-weight:600;\">CREATED BY</span> Hasan Güneş &amp; Onur Gürler</p></body></html>"))
